-- 회원 테이블 생성
CREATE TABLE MEMBER (
	MEMBER_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID VARCHAR(255) NOT NULL UNIQUE ,
    MEMBER_PASSWORD VARCHAR(255) NOT NULL,
    MEMBER_PHONE VARCHAR(255) UNIQUE NOT NULL ,
    MEMBER_EMAIL VARCHAR(255) UNIQUE NOT NULL ,
    MEMBER_NAME VARCHAR(255) NOT NULL ,
    MEMBER_ROLE INT NOT NULL
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
;
-- 회원 프로필 테이블 생성
CREATE TABLE MEMBER_PROFILE (
	MEMBER_NO BIGINT PRIMARY KEY,
    ORI_NAME VARCHAR(255),
    SAVE_NAME VARCHAR(255),
	FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
;
-- 입양문의 테이블 생성
CREATE TABLE QNA (
	
	QNA_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    QNA_TITLE VARCHAR(255) NOT NULL,
    QNA_WRITER VARCHAR(255) NOT NULL,
    QNA_CONTENT LONGTEXT NOT NULL,
    QNA_DATE DATE NOT NULL,
    MEMBER_NO BIGINT NOT NULL,
	FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_NO)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
;
-- QNA 첨부파일 테이블 생성
CREATE TABLE QNAFILE (
	QNA_NO BIGINT NOT NULL,
    ORI_NAME VARCHAR(255) NOT NULL,
    SAVE_NAME VARCHAR(255) NOT NULL,
    FOREIGN KEY (QNA_NO) REFERENCES QNA (QNA_NO)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
;
-- 문의 답글 테이블 생성
CREATE TABLE QNA_REPLY (
    QNA_NO BIGINT PRIMARY KEY,
    REPLY_WRITER BIGINT NOT NULL,
    REPLY_CONTENT VARCHAR(255) NOT NULL,
    REPLY_DATE DATE NOT NULL,
    FOREIGN KEY (QNA_NO) REFERENCES QNA (QNA_NO)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
;
-- 문의답글첨부파일 테이블 생성
CREATE TABLE QNA_REPLY_FILE (
   QNA_NO BIGINT NOT NULL,
   ORI_NAME VARCHAR(255) NOT NULL,
   SAVE_NAME VARCHAR(255) NOT NULL,
   FOREIGN KEY (QNA_NO) REFERENCES QNA_REPLY (QNA_NO)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
;
-- 유기견 테이블 생성
CREATE TABLE DOG(
	DOG_NO BIGINT PRIMARY KEY,
	DOG_NAME VARCHAR(255) NOT NULL,
	DOG_BIRTH DATE NOT NULL,
	DOG_GENDER INT NOT NULL,
	DOG_TYPE VARCHAR(255) NOT NULL,
	DOG_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	DOG_INOCULATION BOOLEAN NOT NULL ,
	DOG_PRICE INT NOT NULL,
	DOG_INFO LONGTEXT
)
ENGINE =InnoDB,
CHARACTER SET = utf8mb4;
-- 유기견 프로필 사진 테이블 생성
CREATE TABLE DOG_PROFILE (
	DOG_NO BIGINT PRIMARY KEY,
    ORI_NAME VARCHAR(255) NOT NULL,
    SAVE_NAME VARCHAR(255) NOT NULL,
    FOREIGN KEY (DOG_NO) REFERENCES DOG(DOG_NO)
)
ENGINE =InnoDB,
CHARACTER SET = utf8mb4;
-- 회원 즐겨찾기 테이블 생성
CREATE TABLE FAVARITES(
	MEMBER_NO BIGINT NOT NULL ,
    DOG_NO BIGINT NOT NULL,
    PRIMARY KEY(MEMBER_NO,DOG_NO ),
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (DOG_NO) REFERENCES DOG(DOG_NO)
)
ENGINE =InnoDB,
CHARACTER SET = utf8mb4;
-- 입양 내역 로그 테이블 생성
CREATE TABLE ADOPTIONLOG(
	ADOPTION_NO BIGINT AUTO_INCREMENT NOT NULL,
    DOG_NO BIGINT NOT NULL,
    MEMBER_NO BIGINT NOT NULL,
	PRIMARY KEY(ADOPTION_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (DOG_NO) REFERENCES DOG(DOG_NO)
)